# Generated by Django 5.2.14 on 2026-05-13 03:38

import django.db.models.deletion
import threads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='accounts.member', verbose_name='发布人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='orders.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '跟帖',
                'verbose_name_plural': '跟帖',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=threads.models.post_attachment_upload_to, verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='threads.post', verbose_name='跟帖')),
            ],
            options={
                'verbose_name': '跟帖附件',
                'verbose_name_plural': '跟帖附件',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
