# Generated by Django 5.2.14 on 2026-05-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='姓名')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='口令哈希')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'ordering': ['name'],
            },
        ),
    ]
