# Generated by Django 5.2.14 on 2026-05-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "退出"),
                            ("member_save", "保存成员"),
                            ("order_create", "创建工单"),
                            ("order_tags_update", "更新工单标签"),
                            ("order_archive_update", "更新归档状态"),
                            ("post_create", "发布跟帖"),
                            ("status_save", "保存状态标签"),
                            ("template_publish", "发布模板"),
                            ("todo_read", "阅读待办"),
                            ("todo_done", "完成待办"),
                        ],
                        max_length=40,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=80, verbose_name="对象类型"),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="对象 ID"
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(blank=True, max_length=160, verbose_name="对象名称"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="详情"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=255, verbose_name="浏览器"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="accounts.member",
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
