# Generated by Django 5.2.14 on 2026-05-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读'), ('done', '已完成')], default='unread', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='orders.workorder', verbose_name='工单')),
                ('source_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='threads.post', verbose_name='来源跟帖')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='accounts.member', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '待办',
                'verbose_name_plural': '待办',
                'ordering': ['status', '-created_at'],
                'unique_together': {('source_post', 'target')},
            },
        ),
    ]
