# Generated by Django 5.2.14 on 2026-05-13 04:02

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='状态名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '工单状态',
                'verbose_name_plural': '工单状态',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='模板名称')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_image_templates', to='accounts.member', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '图片模板',
                'verbose_name_plural': '图片模板',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=80, verbose_name='客户姓名')),
                ('customer_contact', models.CharField(blank=True, max_length=120, verbose_name='联系方式')),
                ('customer_note', models.TextField(blank=True, verbose_name='客户备注')),
                ('customer_data', models.JSONField(blank=True, default=dict, verbose_name='客户信息')),
                ('template_snapshot', models.JSONField(default=dict, verbose_name='图片模板快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='accounts.member', verbose_name='创建人')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.statusoption', verbose_name='状态')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=80, verbose_name='模板字段 key')),
                ('label', models.CharField(max_length=80, verbose_name='图片类别')),
                ('image', models.ImageField(upload_to=orders.models.order_image_upload_to, verbose_name='图片')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.workorder', verbose_name='工单')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_images', to='accounts.member', verbose_name='上传人')),
            ],
            options={
                'verbose_name': '工单图片',
                'verbose_name_plural': '工单图片',
                'ordering': ['template_key', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, verbose_name='字段 key')),
                ('label', models.CharField(max_length=80, verbose_name='图片类别')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('min_count', models.PositiveIntegerField(default=0, verbose_name='最少张数')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.imagetemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '图片模板项',
                'verbose_name_plural': '图片模板项',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CustomerTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, verbose_name='字段 key')),
                ('label', models.CharField(max_length=80, verbose_name='字段名称')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_items', to='orders.imagetemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '客户信息模板项',
                'verbose_name_plural': '客户信息模板项',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
